asr_sdm_video_enhancement_ml_node:
  ros__parameters:
    input_topic: /sensing/camera/camera0/image_raw/compressed
    output_topic: /perception/video_enhancement/image_enhanced/compressed
    normalize_output: true
