/**:
  ros__parameters:
    params_file: config/euroc/euroc_config.yaml
    calibration_file: config/euroc/euroc_cam_calibration.yaml
    config_file: ""
    enable_sparse: true
    sparse_align:
      use_sparse_align: 1
      use_td_pre_calib: 0
      sparse_align_patch_size: 2
      sparse_align_max_level: 1
      sparse_align_min_level: 1
      sparse_align_max_iter: 1
      sparse_align_lambda_rot: 1.0
      sparse_align_lambda_trans: 0.0
      sparse_align_chi2_thresh: 50.0
      sparse_align_min_features: 25
      sparse_align_min_iter_for_ok: 1
    perf:
      klt_reuse_sparse_pyr: 1
      detect_skip_sparse: 3
      detect_skip_min_cnt: 80
      ransac_confidence: 0.99
    namespace: localization/vins
    rviz_config: config/vins_euroc_rviz.rviz
    pose_graph:
      visualization_shift_x: 0
      visualization_shift_y: 0
      skip_cnt: 0
      skip_dis: 0.0

    sparse_rotation_gate:
      enable: false
      angle_thresh_deg: 30.0
      max_yaw_diff_deg: 45.0
      vio_diff_deg: 20.0
      min_inliers: 20
