# Generated by OpenCV CUDA install
export CUDA_HOME="$HOME/.local/cuda-13.3-root/usr/local/cuda-13.3"
export PATH="${CUDA_HOME}/bin:${PATH}"
export LD_LIBRARY_PATH="$HOME/.local/opencv-cuda/lib:$HOME/.local/cuda-13.3-root/usr/local/cuda-13.3/lib64:$HOME/.local/cuda-libs-13.3/usr/local/cuda-13.3/targets/x86_64-linux/lib:${LD_LIBRARY_PATH:-}"
export OpenCV_DIR="$HOME/.local/opencv-cuda/lib/cmake/opencv4"
export PKG_CONFIG_PATH="$HOME/.local/opencv-cuda/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
